# Redis ????
redis.mode=single
redis.host=120.26.198.34
redis.port=6379
redis.password=123456
redis.database=0

# ?????
redis.pool.maxSize=64
redis.pool.minIdle=10
redis.pool.idleTimeout=10000
redis.pool.connectTimeout=3000
redis.pool.commandTimeout=3000

redis.thread.num = 16
NettyThreads.num = 32

# ??????????
# redis.cluster.nodes=10.0.0.1:6379,10.0.0.2:6379
# redis.cluster.scanInterval=2000